# Generated by Django 4.1.3 on 2022-11-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='description_short',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
