# Generated by Django 4.1.3 on 2022-11-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(default='place_id', max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
